# Generated by Django 5.2.7 on 2025-11-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_counted_views_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date'], 'verbose_name': 'POST', 'verbose_name_plural': 'Posts'},
        ),
    ]
